### ISSUE TITLE
Błąd przy uruchamianiu

### ISSUE THREAD

**Issue by ShookTea** [ShookTea/Finanse#31]
System Windows XP Professional
JRE v. 1.7.0_67

Stack:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: st/init/Update : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by ShookTea** [comment]
Błąd spowodowany starą wersją JRE. Należy zaktualizować JRE do najnowszej wersji.
